### ISSUE TITLE
Add a function to stop retries.

### ISSUE THREAD

**Issue by kadishmal** [tim-kos/node-retry#17]
Sometimes it is necessary to stop retrying. For instance, when the retry causes the environment to enter some severe state (remote server returns 500), we really don't want to retry. Would be nice to have a function to accomplish this.

**Comment by tim-kos** [comment]
Hey @kadishmal kadishmal,

well you could just examine the error that was return from the preview attempt and then not call operation.retry(err) again if the error suggests a severe state.

**Comment by kadishmal** [comment]
In my environment, the worker function needs to call another function called `errorHandler()` which needs to some event cleanups before we `retry`. So, I just do the following before calling errorHandler() for places which indicate that no more retries should be done again:

    // As of now, `retry` module doesn't provide a function to
    // stop retries. So, we have to manually alter its private
    // variable.
    retryOperation._timeouts = [];
    errorHandler(err);

So, the suggested function `retryOperation.complete()` or `.halt()` would do the above timeout reseting job.

**Comment by tim-kos** [comment]
Okay, got it.

Well if you create a pull request with this function, a simple test and a Readme update, I'd merge it. :+1:

**Comment by satazor** [comment]
#17 is somewhat related to my use case, but still a useful feature. Though, if I had a "stop" functionality it would resolve my use case.

**Comment by tim-kos** [comment]
@kadishmal Are you still planning to submit a PR for this? :)

**Comment by maxnachlinger** [comment]
Added a simple implementation of ``stop()`` as PR #28

**Comment by tim-kos** [comment]
Hey @kadishmal 

Sorry for the delay here. Could you please explain your use case again to me, but with greater detail? I still cannot fully understand why you need this stop function.

Everything within node-retry works with `setTimeout` and not with `setIntervals`. So in your example:

```
operation.attempt(function(currentAttempt) {
  failingAsyncOperation(someInput, function(err, result) {

    if (err && err.message === 'A fatal error') {
      operation.stop();
      return cb(err);
    }

    if (operation.retry(err)) {
      return;
    }

    cb(operation.mainError(), operation.errors(), result);
  });
});
```

Just make sure you do not call `operation.retry` again if there is a fatal error. That will prevent the next `setTimeout` to be set and you have effectively stopped all retries.

Think of this code:

```
operation.attempt(function(currentAttempt) {
  failingAsyncOperation(someInput, function(err, result) {
    
    if (err && err.message === 'A fatal error') {
      return cb(err);
    }

    if (operation.retry(err)) {
      return;
    }

    cb(operation.mainError(), operation.errors(), result);
  });
});
```

Can you please test this if it gives you the functionality you desire? It should. If it doesn't, then please do explain again.

I appreciate you spending the time on this and submitting a PR. But I am afraid I cannot merge in functionality that I believe is already supported.

**Comment by tim-kos** [comment]
`operation.stop()` was merged quite some time ago.
