### ISSUE TITLE
retries + 1 issue

### ISSUE THREAD

**Issue by cristian-smocot** [tim-kos/node-retry#21]
What am I doing wrong, if the number of attempts is __retries+1__?

I specified the `retries` options parameter to __5__ for example, the it attempts __6__ times to execute the operation.

**Comment by dirkbonhomme** [comment]
Probably 1 attempt and 5 retries?

**Comment by cristian-smocot** [comment]
I get it now. Thanks!

**Comment by tim-kos** [comment]
1 attempt and 5 retries, that's correct!
