### ISSUE TITLE
Option to unref timers

### ISSUE THREAD

**Issue by satazor** [tim-kos/node-retry#26]
Use case:

I have a long running process that use `retry` in various places. This process intercepts `SIGINT` and `SIGTERM` to gracefully do some cleaning before exiting, closing sockets and stuff like that keep the event loop from emptying. Though, the process won't exit if there is a retry running.. and I have to wait for the whole timer duration before exiting.

To solve this we could add an `unref` (true/false) option so that the setTimeout's don't prevent the process from exiting. Would you be willing to add this functionality?

**Comment by satazor** [comment]
Reference: https://nodejs.org/api/timers.html#timers_unref

**Comment by tim-kos** [comment]
Looks good to me, with the exception that it breaks the API now for the RetryOperation initialization. It now awaits an object as the second parameter, whereas before you could use a boolean for `retryForever`.

Could you please add code that fixes this? Something like:

```
if (typeof options == 'boolean') {
   retryForever = options;
   options = {
      retryForever: retryForever,
      unref: false
   }
}
```

Then I'll happily merge this. Thanks for the contribution!

**Comment by satazor** [comment]
@tim-kos done, I've simplified your suggestion a bit: https://github.com/tim-kos/node-retry/pull/27/files#diff-5fbd26cd639da16ee356ed75e5ff2334R2

**Comment by tim-kos** [comment]
<3

**Comment by satazor** [comment]
Cool! Can you please release a new version? Thanks <3

**Comment by tim-kos** [comment]
Done!
