### ISSUE TITLE
Retry.timeouts() are descending when using a factor < 1

### ISSUE THREAD

**Issue by felixge** [tim-kos/node-retry#3]
When using a factor < 1, the longest timeout will come first:

```
> r = require('retry')
{ operation: [Function], timeouts: [Function], _createTimeout: [Function] }
> r.timeouts({factor: 0.5, retries: 3})
[ 1000, 500, 250 ]
```

To fix this, the resulting timeout array should be sorted in ascending order.

--fg

**Comment by rahpuser** [comment]
Inverting the array would not break the maxTimeout ? now the minTimeout would also be the maxTimeout ?
