### ISSUE TITLE
options.forever doesn't honor delay between retries

### ISSUE THREAD

**Issue by m59peacemaker** [tim-kos/node-retry#32]
I have [a module](https://github.com/m59peacemaker/node-try-net-connect) that depends on this. I just discovered that on `forever` retries, there is no delay in between the retries. I don't know how to write an appropriate test for this project, but I'm fairly sure it is on this end.

**Comment by tim-kos** [comment]
I have just tested this and `forever` reuses the timeouts array once all of its timeouts have been used up. So I am pretty sure this is a problem in your code.

Do you mind pastebin'ing it?

**Comment by m59peacemaker** [comment]
In my failing case, retries is null, so that would explain it, right?

https://github.com/m59peacemaker/node-try-net-connect/blob/master/index.js

**Comment by m59peacemaker** [comment]
My failing test (just retries instantly) https://github.com/m59peacemaker/node-try-net-connect/blob/master/test/index.js#L75

**Comment by m59peacemaker** [comment]
Submitted a pull request to fix it https://github.com/tim-kos/node-retry/pull/33

**Comment by tim-kos** [comment]
Merged the PR. Closing this.
