### ISSUE TITLE
1.0?

### ISSUE THREAD

**Issue by chadxz** [tim-kos/node-retry#35]
Thank you so much for this project. I've used it many times and it is my go-to backoff library. 

I was curious, is there anything preventing a 1.0 release at this point? The library seems pretty stable and does its job really well. Bumping it into "stable" semver territory seems like it would be a good thing.

**Comment by tim-kos** [comment]
I agree and I have been thinking about it lately, too. :) You can  expect something soon. 👍

**Comment by chadxz** [comment]
cheers 🍺
