### ISSUE TITLE
Docs: clarify whether `retries: 1` means 'do it once' or 'do it twice'

### ISSUE THREAD

**Issue by craigds** [tim-kos/node-retry#37]
Naïve reading of the docs would suggest `retries: 1` means 'do it once, and then retry it once if it failed'.

Is that what it means? Or is it 'do it once and then stop'?

**Comment by lorenzos** [comment]
> Naïve reading of the docs would suggest retries: 1 means 'do it once, and then retry it once if it failed'.

That's what it do, from my experience. I think it's correct and inferable from the name itself (`retries`), bit I agree that it can be said explicitly in docs.
