### ISSUE TITLE
Support wrap for function object

### ISSUE THREAD

**Issue by solsson** [tim-kos/node-retry#39]
Is there a reason why `wrap` only supports an object with functions as properties, or would it also be possible to take a single function as argument and wrap it?

**Comment by tim-kos** [comment]
It would only make `wrap`'s code a little more complex, but otherwise I see no reason. I'd be happy to accept a PR for this. :)

**Comment by solsson** [comment]
Might do that. We ended up with http://caolan.github.io/async/docs.html#retry now. Let's see what will come out on top :)

**Comment by tim-kos** [comment]
Alright, closing this then as nobody else seems to want this for now.
