### ISSUE TITLE
.wrap() calls last specified function for all calls

### ISSUE THREAD

**Issue by atamon** [tim-kos/node-retry#43]
Hi,

I found that the .wrap() function acts oddly when being called as follows:

```js
var obj = {
  fn1: function () { ... },
  fn2: function () { ... },
};

retry.wrap(obj, { nRetries: 3, randomize: true }, ['fn1', 'fn2']);
```

Both obj.fn1() and obj.fn2() will now call the same original function due to this line https://github.com/tim-kos/node-retry/blob/master/lib/retry.js#L76. The variable `original` will be [hoisted](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/var#var_hoisting) to the top of the function declaration of `wrap`.

I'm going to solve my specific use-case by calling wrap twice, once per function instead. But if you'd like to, I could try to get back with a PR for solving this.

**Comment by tim-kos** [comment]
Yes, I'd be happy to accept a PR for this.

Nice find!

**Comment by tim-kos** [comment]
Hey @atamon 

Would you still like to send a PR for this?

**Comment by atamon** [comment]
Hi @tim-kos! Of course, it slipped my mind back a year ago. Please see #52 for what I had in mind back then.

**Comment by tim-kos** [comment]
Fixed in https://github.com/tim-kos/node-retry/pull/52#pullrequestreview-107541811 Thank you!
