### ISSUE TITLE
would be nice to have option to retry indefinitely

### ISSUE THREAD

**Issue by davepacheco** [tim-kos/node-retry#5]
Sometimes, you want to retry an operation indefinitely.  It would be nice if "Infinity" (or some other special value) could be specified for "retries".  Currently, that causes Node to blow up with out of memory.

**Comment by tim-kos** [comment]
Well, you could also put your retry logic into a function and once it returns, because all retries are exceeded, you call that calling function again to start the retry process again.

**Comment by gunar** [comment]
I'd like to reopen this discussion and have `0` retries mean it should retry indefinitely.

Current implementation is `0` retries equals a single attempt. In my view that's less useful than my suggestion, since if you don't want retries, just don't use `node-retry`.

What do you guys think? Happy to provide PR.

**Comment by davepacheco** [comment]
An option to retry indefinitely is nice.  But for what it's worth, we have programs that use node-retry, and sometimes (based on user configuration) don't want to retry at all.  It's pretty useful to be able to just write the code to use node-retry for the general case and then specify retries=0 when you want that.  `Infinity` is a valid numeric value and actually reflects what you want (i.e., infinite retries)

**Comment by gunar** [comment]
@davepacheco Agreed. Infinity would be perfect but doesn't work:
![Error](https://cloud.githubusercontent.com/assets/7684574/16280784/a9006a3e-3897-11e6-85dc-4a4f86ad6872.png)

**Comment by davepacheco** [comment]
That's because of the way it's implemented now.  I thought you were proposing a change to node-retry.

**Comment by satazor** [comment]
I do also have programs that use 0 so I'm up for infinity. I also think this is a good addition. @tim-kos?

**Comment by gunar** [comment]
@davepacheco would you mind reopening this issue? Thank you!

@tim-kos what do you think about our proposal? do you want me to open a separate issue? Again, happy to provide a PR. Thanks!

**Comment by davepacheco** [comment]
@gunar I don't have permissions to reopen this issue.

**Comment by tim-kos** [comment]
> I'd like to reopen this discussion and have 0 retries mean it should retry indefinitely.

That's definitely backwards-compatibility breaking, so we can't do that, I am sorry.

> what do you think about our proposal? do you want me to open a separate issue? Again, happy to provide a PR. Thanks!

Sure, I have re-opened the issue. Also happy to review and merge a PR. Not sure about `infinity`, though. But maybe some other value would be cool?

**Comment by vrama628** [comment]
What's wrong with using Infinity?

**Comment by satazor** [comment]
While it might look strange, `Infinity` is exactly what we want and it's the best type to express what we really want.. infinite retries.

**Comment by tim-kos** [comment]
Okay, haven't used it myself yet in over 12 years, but I hear you. :)

Anybody up for submitting a PR?

**Comment by xnramx** [comment]
Can someone please explain the diference between ```Infinity```and ```Forever```?

**Comment by satazor** [comment]
Forever? I guess that type doesn't exist.

**Comment by xnramx** [comment]
> **forever**: Whether to retry forever, defaults to false.
https://github.com/tim-kos/node-retry/blob/master/README.md

https://github.com/tim-kos/node-retry/blob/master/test/integration/test-forever.js

**Comment by satazor** [comment]
Oh you are right, this issue is quite old compared to the `forever` option that was recently added. @tim-kos can you clarify if that new option solves what is being discussed here?

**Comment by tim-kos** [comment]
Hey everyone,

Yes, that is exactly what the recently added `forever` does. There is no specified set of timeouts, but rather a minimum and maximum timeout, which is used again and again until you manually call `operation.stop()`.

Just check the test case here, and it should be quite clear: https://github.com/tim-kos/node-retry/blob/master/test/integration/test-forever.js

Closing this issue then now. 👍

**Comment by satazor** [comment]
👍👍👍

**Comment by larsonma** [comment]
Is there an ability to retry forever with increasing time between each attempt rather than a constant timeout? For example, could I start with minTimeout at 1000, use a factor of 2, and then cap the time between intervals at a maxTimeout (allowing retries to continue forever at maxTimeout).
