### ISSUE TITLE
new method retry.wrap

### ISSUE THREAD

**Issue by kof** [tim-kos/node-retry#6]
I am often writing the same stuff over and over, this function would reduce a lot, but it is only possible to implement it based on 2 conventions:
    - callback is always the last argument
    - err is always the first argument

So basically I want to say: wrap all functions of object `obj` into retry logic, use `opts` for retry options, optionally `props` is a list of props I need to wrap, otherwise wrap all functions.

    retry.wrap(opts, obj, props)

Would you accept a pull request implementing this?

**Comment by tim-kos** [comment]
Will finish this and merge the related PR.
