### ISSUE TITLE
When is the next release (with changes from master) scheduled to go out to npm? 

### ISSUE THREAD

**Issue by ali-sharif** [tim-kos/node-retry#78]

**Comment by wizo06** [comment]
@tim-kos bumping this.

@ali-sharif in the meantime, you can install directly from github repo with
```
npm i tim-kos/node-retry
```

**Comment by ArGeoph** [comment]
@tim-kos I was also wondering when a new version will be available? Badly need some of the bug fixes that are in master right now.

Let me know if I can help with anything to speed up the release.

**Comment by tim-kos** [comment]
Sorry for the delay here. Will try to get it done this Saturday.

**Comment by badrange** [comment]
Friendly reminder @tim-kos that a few Saturdays have passed since this issue was created :-)

**Comment by tim-kos** [comment]
Version 0.13.1 contains that code and was released on June 21, 2021. :)
<https://github.com/tim-kos/node-retry/releases/tag/v0.13.1>
